### load summary statistics RData file generated by genomicSEM
load("sumstats.RData")

### split the summary statistics SNPs into smaller sets so that they can be processed faster (this one splits into sets of 8000)
split_sumstats <- split(sumstats, (as.numeric(rownames(sumstats))-1) %/% 8000)
### save each data frame as its own text file
lapply(names(split_sumstats), function(x){write.table(split_sumstats[[x]], file = paste("./split_sumstats/sumstats", x,".txt", sep = ""), quote = FALSE, row.names=FALSE)})


### determine number of SNP sets and then save to a file
num_SNP_sets <- length(split_sumstats)
write.table(num_SNP_sets, file="num_SNP_sets.txt", row.names=FALSE, col.names=FALSE, quote=FALSE)
