### load summary statistics RData file generated by genomicSEM
load("sumstats.RData")

### split the summary statistics SNPs into smaller sets so that they can be processed faster
### save the new list of dataframes as .RData file
split_sumstats <- split(sumstats, (as.numeric(rownames(sumstats))-1) %/% 8000)
save(split_sumstats, file="split_sumstats.RData")

### determine number of SNP sets and then save to a file
num_SNP_sets <- length(split_sumstats)
write.table(num_SNP_sets, file="num_SNP_sets.txt", row.names=FALSE, col.names=FALSE, quote=FALSE)
